#!/usr/bin/env python3
"""Wrapper for clang-tidy invoked via CMAKE_CXX_CLANG_TIDY.

CMake (via ``cmake -E __run_co_compile``) calls this wrapper instead of
clang-tidy directly. The wrapper:

1. Receives the real clang-tidy path as ``argv[1]``.
2. Splits the rest into clang-tidy options (before ``--``) and the cl.exe
   compile command (after ``--``).
3. **Skips linting entirely** on Qt-generated translation units (qrc_*,
   moc_*, *plugin_init.cpp, .qt/* artifacts) — they're machine-generated
   and trip identifier-naming/internal-linkage checks for no real reason.
4. **Lifts** the flags clang-tidy needs at parse time
   (``-external:I<path>`` Qt includes, ``/std:c++17``, ``/Zc:__cplusplus``,
   ``/permissive-``) out of the compile command and re-adds them as
   ``--extra-arg=...`` clang-tidy options placed before ``--``. Anything
   left inside the compile command under ``--driver-mode=cl`` is routed
   through clang-cl, which silently drops these particular flags — Qt
   include roots fail to resolve and ``__cplusplus`` stays at C++14, so
   ``<QtCore>`` then bails with ``Qt requires a C++17 compiler``. Lifting
   them via ``--extra-arg=`` makes clang-tidy apply them in its own
   driver, independent of cl-mode parsing.
5. **Drops** other MSVC-only switches clang-cl can't parse:
   ``-external:W*``, ``/analyze`` family, ``-FS``, ``-utf-8``, ``/showIncludes``.
6. **Normalizes** dash-prefixed MSVC switches clang-cl only recognizes in
   slash form: ``-MDd`` -> ``/MDd`` (etc.). The ``-std:``/``-Zc:``/
   ``-permissive`` family is normalized then lifted via step 4.
7. Re-invokes the real clang-tidy with the rewritten command.

``HeaderFilterRegex`` in ``.clang-tidy`` restricts diagnostics to our
``src/`` tree, so warnings inside Qt headers stay suppressed.
"""
from __future__ import annotations

import re
import subprocess  # nosec B404 — wraps clang-tidy, vendor binary path is verified by caller
import sys

# ---------------------------------------------------------------------------
# Qt-generated translation units. Clang-tidy is skipped on these entirely;
# they're machine-emitted and produce only noise against our strict checks.
# ---------------------------------------------------------------------------
_GENERATED_PATTERNS: tuple[re.Pattern[str], ...] = (
    # Catch-all: every TU emitted under build/ is autogenerated (autogen,
    # qmlcache, qmltyperegistrations, plugin init, qmltypes, MOC, qrc).
    # Our hand-written code lives in src/ and qml/ — never in build/.
    re.compile(r"[\\/]build[\\/]", re.IGNORECASE),
    # Keep the specific patterns too, in case a generator emits outside of
    # build/ (e.g. for a different preset path or in-source generation).
    re.compile(r"[\\/]\.qt[\\/]", re.IGNORECASE),
    re.compile(r"[\\/]\.rcc[\\/]", re.IGNORECASE),
    re.compile(r"[\\/][^\\/]*_autogen[\\/]", re.IGNORECASE),
    re.compile(r"(^|[\\/])moc_[^\\/]+\.cpp$", re.IGNORECASE),
    re.compile(r"(^|[\\/])qrc_[^\\/]+\.cpp$", re.IGNORECASE),
    re.compile(r"(^|[\\/])ui_[^\\/]+\.cpp$", re.IGNORECASE),
    re.compile(r"(^|[\\/])mocs_compilation[^\\/]*\.cpp$", re.IGNORECASE),
    re.compile(r"(^|[\\/])[^\\/]*qmlcache_loader\.cpp$", re.IGNORECASE),
    re.compile(r"(^|[\\/])[^\\/]*_qmltyperegistrations\.cpp$", re.IGNORECASE),
    re.compile(r"[\\/][^\\/]+_qml\.cpp$", re.IGNORECASE),
    re.compile(r"(^|[\\/])\w+plugin[^\\/]*\.cpp$", re.IGNORECASE),
)

# Drop these compile-cmd switches entirely (both - and / forms).
_STRIP_PREFIXES: tuple[str, ...] = (
    "-analyze",   "/analyze",
)
_STRIP_EXACT: frozenset[str] = frozenset({
    "-FS", "/FS",
    "-utf-8", "/utf-8",
    "-showIncludes", "/showIncludes",
})

# MSVC switches clang-cl only knows in slash form. Rewrite dash variants.
_NORMALIZE_PREFIXES: tuple[str, ...] = (
    "-std:",
    "-Zc:",
    "-MDd", "-MD", "-MTd", "-MT",
    "-permissive-", "-permissive",
    "-await",
)

# Switches clang-tidy must see at parse time but which clang-cl silently
# drops if left in the compile cmd. Lifted into --extra-arg= after
# normalization so clang-tidy's own driver applies them.
_LIFT_PREFIXES: tuple[str, ...] = (
    "/std:", "-std:",
    "/Zc:", "-Zc:",
    "/permissive", "-permissive",
)


def _is_generated_source(path: str) -> bool:
    return any(p.search(path) for p in _GENERATED_PATTERNS)


def _normalize(arg: str) -> str:
    if not arg.startswith("-"):
        return arg
    for p in _NORMALIZE_PREFIXES:
        if arg.startswith(p):
            return "/" + arg[1:]
    return arg


def _filter_compile_args(
        args: list[str]) -> tuple[list[str], list[str]]:
    """Strip / rewrite MSVC switches; lift external includes for the driver.

    Returns (compile_args, extra_tidy_args). The compile args are what stays
    after ``--``; the extra tidy args (``--extra-arg=-I<path>``) are inserted
    before ``--`` so clang-tidy's own driver resolves Qt headers regardless
    of cl-mode parsing quirks.
    """
    compile_out: list[str] = []
    extra_tidy: list[str] = []
    for arg in args:
        # Lift -external:I<path> to clang-tidy's --extra-arg=-I<path>.
        # See module docstring for why we don't keep these in the compile cmd.
        if arg.startswith("-external:I") or arg.startswith("/external:I"):
            path = arg.split(":I", 1)[1]
            extra_tidy.append(f"--extra-arg=-I{path}")
            continue
        # Drop other -external: variants (W0, anglebrackets, templates-, etc).
        if arg.startswith("-external:") or arg.startswith("/external:"):
            continue
        if arg in _STRIP_EXACT:
            continue
        if any(arg.startswith(p) for p in _STRIP_PREFIXES):
            continue
        # Lift C++-language-mode flags to clang-tidy's own driver.
        if any(arg.startswith(p) for p in _LIFT_PREFIXES):
            extra_tidy.append(f"--extra-arg={_normalize(arg)}")
            continue
        compile_out.append(_normalize(arg))
    return compile_out, extra_tidy


def _find_source_file(args: list[str]) -> str | None:
    """The compile-target path is whatever sits in args before `--`."""
    if "--" not in args:
        return None
    head = args[:args.index("--")]
    # clang-tidy convention: positional source file appears in head, after
    # any --extra-arg-before=... options. Scan from the end.
    for arg in reversed(head):
        if arg.startswith("-"):
            continue
        return arg
    return None


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: clang_tidy_wrapper.py <clang-tidy-path> [args...]",
              file=sys.stderr)
        return 2

    real_tidy = sys.argv[1]
    args = sys.argv[2:]

    source = _find_source_file(args)
    if source is not None and _is_generated_source(source):
        # Qt autogen file — skip linting, return success.
        return 0

    if "--" in args:
        sep = args.index("--")
        head = args[:sep]
        compile_cmd = args[sep + 1:]
        compile_filtered, extra_tidy = _filter_compile_args(compile_cmd)
        new_args = [*head, *extra_tidy, "--", *compile_filtered]
    else:
        new_args = args

    return subprocess.run([real_tidy, *new_args]).returncode  # nosec B603 B607 — real_tidy is the resolved clang-tidy path passed in by CMake


if __name__ == "__main__":
    sys.exit(main())
